crawl:
  max_pages: null
  timeout_sec: 10
  user_agent: AQaTestBot/0.1
  same_domain_only: true
generate:
  output_dir: tests/generated
  file_prefix: test_generated_
  include_prints: true
  include_comments: true
  link_assertions_max: 10
  link_match_strategy: contains
last_crawl:
  domain: www.delta.com
  count: 1
selenium:
  browser: chrome
  headless: false
  window_size: 1366,900
  page_load_timeout_sec: 20
  implicit_wait_sec: 2
last_generated_file: tests/generated\test_generated_www_delta_com.py
