crawl:
  max_pages: null
  timeout_sec: 10
  user_agent: AQaTestBot/0.1
  same_domain_only: true
generate:
  output_dir: tests/generated
  file_prefix: test_generated_
  include_prints: true
  include_comments: true
  link_assertions_max: 10 # max links per page to assert
  link_match_strategy: "contains" # "contains" | "exact"
last_crawl:
  domain: www.delta.com
  count: 1
selenium:
  browser: chrome
  headless: false
  window_size: 1366,900
  page_load_timeout_sec: 20
  implicit_wait_sec: 2
